ALTER TABLE settings
  ADD COLUMN IF NOT EXISTS discount_ranked INT NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS discount_coach  INT NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS night_premium   INT NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS night_starts    INT NOT NULL DEFAULT 18;
